### PR TITLE
TOOLBOX_PATH check in noise estimation

### PR DESCRIPTION
**Pull request by sidward**

### CODE REVIEW

**Comment by sidward** [comment]
apt-get is throwing an error? How do I fix this?

**Comment by jtamir** [comment]
I restarted the job on Travis.

Jon

**Comment by sidward** [comment]
Thanks Jon. All tests have passed now.

**Comment by uecker** [comment]
Hi Jon! Stupid question: How did you restart the job on travis? (please don't merge this pull request, I will cherry-pick the commit - I don't want to have two commits for every minor change) Actually, I think the pull request system of GitHub sucks....

**Comment by jtamir** [comment]
> Hi Jon! Stupid question: How did you restart the job on travis?


There's a small button in the top right of the job page that is either an X
for cancel or a rotating arrow for restart.
I'd like to know if pull-requesters, e.g. Sid, can restart jobs for their
branch.


Jon

**Comment by uecker** [comment]
I see it now, I wasn't logged in automatically... 

There is a way for pull-requesters but it is not convenient. See the last comment:
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by sidward** [comment]
How would you rather I submit the changes?

**Comment by uecker** [comment]
It was a complaint about Github, not about you...  Actually, there is a squash feature which helps in this case.

**Pull request merged**
