### PR TITLE
Move regularization options to separate file

### PR DESCRIPTION
**Pull request by jtamir**

### CODE REVIEW

**Comment by uecker** [comment]
Looks good, but please split off the 'resolve circular library dependencies' into its own commit (why do we need this now?) and also please reformat the files according to the indentation style used in BART (indentation with TAB and if it matters TAB= 8 spaces).

**Comment by jtamir** [comment]
Separated out the two commits and fixed the indents. The linking fails on linux (GNU ld tool) because of circular dependencies introduced with optreg.c -- libiter now depends on liblowrank, libwavelet, etc. There is probably a way to resolve them by repeating the library names. The reason for the special-case for OS X is that the LLVM ld tool does not run in to circular dependencies.

See https://travis-ci.org/mrirecon/bart/builds/131772708 for an example of the build failing without the commit

**Comment by jtamir** [comment]
Maybe it makes more sense to keep opt-reg separate from libiter, so there are no cross-library dependencies

**Comment by uecker** [comment]
Moving it to grecon would make sense then.

**Comment by jtamir** [comment]
Should be good now

**Pull request merged**
