### PR TITLE
Added  linop to split complex arrays into real and imaginary.

### PR DESCRIPTION
**Pull request by sidward**
- Add "cri" operator that splits a complex array into the real and imaginary.
- wshfl and wave edited to include "cri" operator.

### CODE REVIEW

**Comment by sidward** [comment]
Please ignore for now. I need to debug a little.

**Comment by sidward** [comment]
Okay, I think it is correct now.

**Comment by sidward** [comment]
Okay, sounds good. Where would I put the md function in with ```num/flpmath```?

**Comment by sidward** [comment]
Okay, from talking to Jon, I think I'd like to commit this as it is now and look into an md implentation down the line if that's okay!

**Comment by uecker** [comment]
Can you please remove the comparisons to true, i.e.  'if (x == true)' should be just 'if (x)' and also try to adapt to the coding style (doc/style.txt). Also please rebase into proper logical commits. Having bug fix commits in the history is not very useful and annoying when later bisecting a problem.

**Comment by sidward** [comment]
I will rebase all the commits into a single commit after confirming a few questions with you. I've updated the `if(x)` you asked for.

1. Do you want me to change my use of `_Complex_I`? If yes, I would like to define a constant in `misc` similar to `M_PI`.
2. Do you want me to change my point arithmetic in `cri_fwd`?
3. Do you not like `cri` as a name for the operator? I couldn't think of a name, so I settled on "complex-real-imaginary".
4. Did I miss anything? For almost all the code, I tried to replicate existing code files.

**Comment by uecker** [comment]
1. Please simply use '1.i '
2. Ideally, use md_ functions, but you can leave this for later.
3. How about 'decompose_complex' ?
4. Don't make a single commit. Use several logical commits. Adding the operator should be one, using it in your code a second. Other stuff should go into their own commits.

**Comment by sidward** [comment]
Does this look okay?

**Comment by uecker** [comment]
yes, thanks

**Pull request merged**
