### PR TITLE
hands_on_materials

### PR DESCRIPTION
**Pull request by EfratShimron**
BART hands-on material page (tutorials.html) added. It includes links to all the recent demos, webinars and git repos (2016-2022).

### CODE REVIEW

**Comment by uecker** [comment]
Thanks Efrat!  This branch cannot be merged due to conflicts. I tried to fix this using the github interface, but this did not work. Can you make a clean pull request (you can remove my merge commit)?

**Comment by EfratShimron** [comment]
Hi Martin,

Thanks for your email. Since you said that the branch cannot be merged, I'm
not sure what you mean by making a clean pull request.
Could you please give me more specific instructions?

Thank you,
Efrat

**Comment by jtamir** [comment]
@EfratShimron to do a rebase locally first, something like: `git pull --rebase origin/gh-pages`. If all went well, you can then `push -f` to your remote branch and the PR should update.

**Comment by uecker** [comment]
Thanks, Efrat! 
A couple of minor things I noticed:
* There are some typos in the quick links: "Referencess" and "List of features" - "List of Features".  
* And can you make the fonts as large as they were? It looks a bit too small too me.
* The quick example with the binder link should be on the home page I think.
* Only the tutorials page has the title changing (and it should be capitalized)
* There is a line missing on the home page below the quick links
* The image is jumping around a bit when clicking on the links, so there is probably something different between the pages.

**Comment by EfratShimron** [comment]
Hi Martin,
I fixed the issues you mentioned, please take a look.
btw I think that the image could be jumping around due to browser issues, because not all of the sub-pages have the same length. I made sure that the html code of the different sub-pages is identical for the top part.

**Pull request merged**
