### PR TITLE
Added python3 bartview and PYTHONPATH instructions to the README

### PR DESCRIPTION
**Pull request by sidward**
- Adds a version of bartview that can be called with python3. 
- Also updates the python instructions to encourage updating PYTHONPATH.

### CODE REVIEW

**Comment by uecker** [comment]
Thanks, Sid! Shouldn't there be an additional copyright header for MIT in bartview3 ? Or has this been created in Berkeley?

**Comment by sidward** [comment]
Apologies. Since I made very small changes, I didn't think much of it. I have updated the code to include the copyright and merged the previous commit with the copyright commit into one.

**Comment by uecker** [comment]
If the changes are very small it is OK without copyright.

**Comment by sidward** [comment]
I've talked to my advisor and updated the copyright in accordance to what he told me!

**Pull request merged**
