### PR TITLE
Wave shuffling with GPU

### PR DESCRIPTION
**Pull request by sidward**
- Added support for wave-shuffling with GPU.
- Kernel adjoint now calls md_fmacc2 in a parallel loop.
- Minor cosmetic changes.

### CODE REVIEW

**Comment by sidward** [comment]
Please don't commit this just yet. I will be making a few more changes.

**Comment by sidward** [comment]
Any suggestions on the error? clang doesn't like that I've used openmp.
```
/home/travis/build/mrirecon/bart/src/wshfl.o: In function `kern_adjoint':
/home/travis/build/mrirecon/bart/src/wshfl.c:(.text+0x3605): undefined reference to `omp_get_max_threads'
/home/travis/build/mrirecon/bart/src/wshfl.c:(.text+0x380e): undefined reference to `omp_get_thread_num'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [wshfl] Error 1
make[1]: Leaving directory `/home/travis/build/mrirecon/bart'
make: *** [test] Error 2
```

**Comment by jtamir** [comment]
I think the clang test is compiled without openmp. You should use openmp guards for this. See `src/num/mem.c` for example

**Comment by jtamir** [comment]
Also - you can test this locally by turning off openmp in the Makefile and running `make test`. Similarly for other Makefile options

**Comment by sidward** [comment]
Gotcha, thanks! I think I pushed the same fix right around when you commented.

**Pull request merged**
