### PR TITLE
Added some error checking to estimate-variance

### PR DESCRIPTION
**Pull request by sidward**

### CODE REVIEW

**Comment by sidward** [comment]
I'm not sure why there are all the commits from when I synced my fork to this branch. Do you know how I can remove it (if needed)?

**Comment by uecker** [comment]
The question is how you got all the new commits? You didn't merge because there is no merge commit. You did not rebase, because then your commit would be the newest. What did you do?
Anyway, you should rebase against bart/master.

**Comment by jtamir** [comment]
I think something funky happened with the steepest-descent branch. If you
look at it, it has some commits that were previously in master.

Jon

**Comment by uecker** [comment]
Yes, Frank changed it, but this is unrelated to Sid's branch.

Am Sonntag, den 14.02.2016, 12:20 -0800 schrieb Jon Tamir:

**Pull request closed without merging**
