### PR TITLE
make custom Makefiles dir and README for explanation

### PR DESCRIPTION
**Pull request by jtamir**
Note: requires moving Makefile.local and Makefile.<machinename> to the Makefiles/ directory

### CODE REVIEW

**Comment by jtamir** [comment]
Here's an example where I find this useful:

https://github.com/jtamir/cpd/tree/cpd-bart

**Comment by uecker** [comment]
I would rather have people contribute back...

**Comment by uecker** [comment]
Let's keep including Makefile.$(NNAME) and Makefile.local in the toplevel and simply include everything in Makefiles/* 

Personally, I like to keep my Makefile.local in the toplevel and Ialso  do not like that it would fail for machines which happend to be called localsomething  (unlikely, but still).

**Comment by jtamir** [comment]
> I would rather have people contribute back...

Yes, but not everything is ready to be contributed back, may be in a private repo, etc. At some point it's easy to merge in.

> Let's keep including Makefile.$(NNAME) and Makefile.local in the toplevel and simply include everything in Makefiles/*

Okay, will change

**Comment by jtamir** [comment]
Rebased

**Pull request merged**
